telegram:
  token: "8455333322:AAEda2OU1klkkl4pRc2GF7DtaSE5B1ok7Cw"
  chat_id: "6023965279"

brokers:
  justmarkets_demo:
    login: 2001257360
    password: "Tapiwanashi@1"
    server: "JustMarkets-Demo"

  weltrade_demo:
    login: 19445845
    password: "kR7(5Gw("
    server: "Weltrade-Demo"
